#!/bin/bash


MAC_ADDRESS="MAC_ADDRESS=3";

../../../tools/infomem.py $MAC_ADDRESS Z_CHANNELS=32768 Z_PAN_ID=243 Z_MAX_CHILDREN=4 Z_MAX_ROUTERS=4 Z_MAX_DEPTH=7 Z_BEACON_ORDER=6 Z_SUPERFRAME_ORDER=0 Z_SCAN_ORDER=6 ALIVE_SEND_PERIOD=20 ALIVE_SEND_ATTEMPTS=3
