from sysobj_generator import *

profile =\
[
		{
		"num":0x24, 
		"name":"SMOKE_DENSITY",
		"size":16,
		"range":whole_range,
		"thresholds":(
            {"name":"PRE_FIRE_DAY", "default":(100, 120), "active":(True, True) }, 
            {"name":"FIRE_DAY", "default":(150, 170), "active":True}, 
            {"name":"PRE_FIRE_NIGHT","default":(50, 70), "active":False}, 
            {"name":"FIRE_NIGHT", "default":(100, 120), "active":False}),
		"network_acces":"r",
		"object_access":"rw",
		},
		{
		"num":0x4a, 
        "name":"FAILURE",
		"size":16,
		"range":whole_range,
		"thresholds":(
            {"name":"PRE_CONTAMINATION", "default":(100, 140), "active":True}, 
            {"name":"CONTAMINATION", "default":(120, 170), "active":True}, 
            {"name":"PRE_FAILURE", "default":(-140, -100), "active":True}, 
            {"name":"FAILURE", "default":(-170, -120), "active":True}),
		"network_acces":"r",
		"object_access":"rw",
		},
		{
		"num":0xE2,
		"name":"CURRENT_STATE",
		"size":16,
		"range":whole_range,  # complex condition
		"thresholds":None,
		"network_acces":"rw", # WHY !?!
		"object_access":"rw",
        #"default":"FIX_ME",
		},
		{
		"num":0xE3,
		"name":"DAY_TIME",
		"size":16,
		"range":IntRange(0,24*60),
		"thresholds":None,
		"network_acces":"rw",
		"object_access":"rw",
        "default":480
		},
		{
		"num":0xE4,
		"name":"NIGHT_TIME",
		"size":16,
		"range":IntRange(0,24*60),
		"thresholds":None,
		"network_acces":"rw",
		"object_access":"rw",
        "default":1200,
		},
		{
		"num":0xE6,
		"name":"BACKGROUND_SIGNAL",
		"size":16,
		"range":whole_range,
		"thresholds":None,
		"network_acces":"r",
		"object_access":"rw",
        "flash":True,
        "default":"0x00D2",
		},
		{
		"num":0xE7,
		"name":"FULL_RANGE_SIGNAL",
		"size":16,
		"range":whole_range,
		"thresholds":None,
		"network_acces":"r",
		"object_access":"rw",
        "flash":True,
        "default":"0x0741",
		},
		{
		"num":0xE8,
		"name":"CONTAMINATION_OFFSET",
		"size":16,
		"range":whole_range,
		"thresholds":None,
		"network_acces":"r",
		"object_access":"rw",
        "flash":True,
        "default":0,
		},
		{
		"num":0xE9,
		"name":"MAX_CONTAMINATION_OFFSET",
		"size":16,
		"range":whole_range,
		"thresholds":None,
		"network_acces":"r",
		"object_access":"rw",
        "flash":True,
        "default":"0x07ED",
		},
		{
		"num":0xEA,
		"name":"MIN_CONTAMINATION_OFFSET",
		"size":16,
		"range":whole_range,
		"thresholds":None,
		"network_acces":"r",
		"object_access":"rw",
        "flash":True,
        "default":"0xFF6E",
		},
		{
		"num":0xEB,
		"name":"FAILURE_INDICATION_MODE",
		"size":8,
		"range":whole_range,
		"thresholds":None,
		"network_acces":"rw",
		"object_access":"",
        "default":"0xFF",
		},
		{
		"num":0xEC,
		"name":"ALARM_INDICATION_MODE",
		"size":8,
		"range":whole_range,
		"thresholds":None,
		"network_acces":"rw",
		"object_access":"",
        "default":"0x7F",
		},
]

generate(profile, 0x8001)

