#define SMOKE_DENSITY                 0x24
#define SMOKE_DENSITY_SIZE            2

#define SMOKE_DENSITY_THR_ACTIVE_LEVELS 0x25
#define SMOKE_DENSITY_THR_ACTIVE_LEVELS_SIZE 2

#define SMOKE_DENSITY_THR_TRIGGERED_LEVELS 0x26
#define SMOKE_DENSITY_THR_TRIGGERED_LEVELS_SIZE 2

#define SMOKE_DENSITY_UPPER_THR_PRE_FIRE_DAY 0x2A
#define SMOKE_DENSITY_UPPER_THR_PRE_FIRE_DAY_SIZE 2

#define SMOKE_DENSITY_LOWER_THR_PRE_FIRE_DAY 0x2B
#define SMOKE_DENSITY_LOWER_THR_PRE_FIRE_DAY_SIZE 2

#define SMOKE_DENSITY_UPPER_THR_FIRE_DAY 0x2C
#define SMOKE_DENSITY_UPPER_THR_FIRE_DAY_SIZE 2

#define SMOKE_DENSITY_LOWER_THR_FIRE_DAY 0x2D
#define SMOKE_DENSITY_LOWER_THR_FIRE_DAY_SIZE 2

#define SMOKE_DENSITY_UPPER_THR_PRE_FIRE_NIGHT 0x2E
#define SMOKE_DENSITY_UPPER_THR_PRE_FIRE_NIGHT_SIZE 2

#define SMOKE_DENSITY_LOWER_THR_PRE_FIRE_NIGHT 0x2F
#define SMOKE_DENSITY_LOWER_THR_PRE_FIRE_NIGHT_SIZE 2

#define SMOKE_DENSITY_UPPER_THR_FIRE_NIGHT 0x30
#define SMOKE_DENSITY_UPPER_THR_FIRE_NIGHT_SIZE 2

#define SMOKE_DENSITY_LOWER_THR_FIRE_NIGHT 0x31
#define SMOKE_DENSITY_LOWER_THR_FIRE_NIGHT_SIZE 2

#define FAILURE                       0x4A
#define FAILURE_SIZE                  2

#define FAILURE_THR_ACTIVE_LEVELS     0x4B
#define FAILURE_THR_ACTIVE_LEVELS_SIZE 2

#define FAILURE_THR_TRIGGERED_LEVELS  0x4C
#define FAILURE_THR_TRIGGERED_LEVELS_SIZE 2

#define FAILURE_UPPER_THR_PRE_CONTAMINATION 0x50
#define FAILURE_UPPER_THR_PRE_CONTAMINATION_SIZE 2

#define FAILURE_LOWER_THR_PRE_CONTAMINATION 0x51
#define FAILURE_LOWER_THR_PRE_CONTAMINATION_SIZE 2

#define FAILURE_UPPER_THR_CONTAMINATION 0x52
#define FAILURE_UPPER_THR_CONTAMINATION_SIZE 2

#define FAILURE_LOWER_THR_CONTAMINATION 0x53
#define FAILURE_LOWER_THR_CONTAMINATION_SIZE 2

#define FAILURE_UPPER_THR_PRE_FAILURE 0x54
#define FAILURE_UPPER_THR_PRE_FAILURE_SIZE 2

#define FAILURE_LOWER_THR_PRE_FAILURE 0x55
#define FAILURE_LOWER_THR_PRE_FAILURE_SIZE 2

#define FAILURE_UPPER_THR_FAILURE     0x56
#define FAILURE_UPPER_THR_FAILURE_SIZE 2

#define FAILURE_LOWER_THR_FAILURE     0x57
#define FAILURE_LOWER_THR_FAILURE_SIZE 2

#define CURRENT_STATE                 0xE2
#define CURRENT_STATE_SIZE            2

#define DAY_TIME                      0xE3
#define DAY_TIME_SIZE                 2

#define NIGHT_TIME                    0xE4
#define NIGHT_TIME_SIZE               2

#define BACKGROUND_SIGNAL             0xE6
#define BACKGROUND_SIGNAL_SIZE        2

#define FULL_RANGE_SIGNAL             0xE7
#define FULL_RANGE_SIGNAL_SIZE        2

#define CONTAMINATION_OFFSET          0xE8
#define CONTAMINATION_OFFSET_SIZE     2

#define MAX_CONTAMINATION_OFFSET      0xE9
#define MAX_CONTAMINATION_OFFSET_SIZE 2

#define MIN_CONTAMINATION_OFFSET      0xEA
#define MIN_CONTAMINATION_OFFSET_SIZE 2

#define FAILURE_INDICATION_MODE       0xEB
#define FAILURE_INDICATION_MODE_SIZE  1

#define ALARM_INDICATION_MODE         0xEC
#define ALARM_INDICATION_MODE_SIZE    1

