#define ANALOG_INPUT1                 0x24
#define ANALOG_INPUT1_SIZE            2

#define ANALOG_INPUT1_THR_ACTIVE_LEVELS 0x25
#define ANALOG_INPUT1_THR_ACTIVE_LEVELS_SIZE 2

#define ANALOG_INPUT1_THR_TRIGGERED_LEVELS 0x26
#define ANALOG_INPUT1_THR_TRIGGERED_LEVELS_SIZE 2

#define ANALOG_INPUT1_UPPER_THR_THRESHOLD1 0x2A
#define ANALOG_INPUT1_UPPER_THR_THRESHOLD1_SIZE 2

#define ANALOG_INPUT1_LOWER_THR_THRESHOLD1 0x2B
#define ANALOG_INPUT1_LOWER_THR_THRESHOLD1_SIZE 2

#define ANALOG_INPUT2                 0x4A
#define ANALOG_INPUT2_SIZE            2

#define ANALOG_INPUT2_THR_ACTIVE_LEVELS 0x4B
#define ANALOG_INPUT2_THR_ACTIVE_LEVELS_SIZE 2

#define ANALOG_INPUT2_THR_TRIGGERED_LEVELS 0x4C
#define ANALOG_INPUT2_THR_TRIGGERED_LEVELS_SIZE 2

#define ANALOG_INPUT2_UPPER_THR_THRESHOLD1 0x50
#define ANALOG_INPUT2_UPPER_THR_THRESHOLD1_SIZE 2

#define ANALOG_INPUT2_LOWER_THR_THRESHOLD1 0x51
#define ANALOG_INPUT2_LOWER_THR_THRESHOLD1_SIZE 2

#define ANALOG_INPUT3                 0x70
#define ANALOG_INPUT3_SIZE            2

#define ANALOG_INPUT3_THR_ACTIVE_LEVELS 0x71
#define ANALOG_INPUT3_THR_ACTIVE_LEVELS_SIZE 2

#define ANALOG_INPUT3_THR_TRIGGERED_LEVELS 0x72
#define ANALOG_INPUT3_THR_TRIGGERED_LEVELS_SIZE 2

#define ANALOG_INPUT3_UPPER_THR_THRESHOLD1 0x76
#define ANALOG_INPUT3_UPPER_THR_THRESHOLD1_SIZE 2

#define ANALOG_INPUT3_LOWER_THR_THRESHOLD1 0x77
#define ANALOG_INPUT3_LOWER_THR_THRESHOLD1_SIZE 2

#define ANALOG_INPUT4                 0x96
#define ANALOG_INPUT4_SIZE            2

#define ANALOG_INPUT4_THR_ACTIVE_LEVELS 0x97
#define ANALOG_INPUT4_THR_ACTIVE_LEVELS_SIZE 2

#define ANALOG_INPUT4_THR_TRIGGERED_LEVELS 0x98
#define ANALOG_INPUT4_THR_TRIGGERED_LEVELS_SIZE 2

#define ANALOG_INPUT4_UPPER_THR_THRESHOLD1 0x9C
#define ANALOG_INPUT4_UPPER_THR_THRESHOLD1_SIZE 2

#define ANALOG_INPUT4_LOWER_THR_THRESHOLD1 0x9D
#define ANALOG_INPUT4_LOWER_THR_THRESHOLD1_SIZE 2

#define ANALOG_INPUT1_TEST            0xE2
#define ANALOG_INPUT1_TEST_SIZE       2

#define ANALOG_INPUT2_TEST            0xE3
#define ANALOG_INPUT2_TEST_SIZE       2

#define ANALOG_INPUT3_TEST            0xE4
#define ANALOG_INPUT3_TEST_SIZE       2

#define ANALOG_INPUT4_TEST            0xE5
#define ANALOG_INPUT4_TEST_SIZE       2

